### ISSUE TITLE
Need to make decision on pangeo vs simpler image for AKS

### ISSUE THREAD

**Issue by blindjesse** [csp-inc/lumonitor#11]
I hate big images but it ~would~ could be easier. Or just convince @ohiat to pass me a client address I can use? Or use an existing AKS pangeo cluster and just create a dask cluster on top of it? (See slack convos).

**Comment by ohiat** [comment]
I think we should be running jobs on a shared AKS cluster. Each user creates their own dask cluster from jupyter/python session

**Comment by blindjesse** [comment]
Going with @ohiat's suggestion if/when this happens
